name: coverage scan

on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:  [15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: yarn install
      - run: yarn build
      - run: yarn express:run &
             sleep 5 && yarn coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.lcov
  scan:
    name: scan
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: coverage
      - uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR }}
          SONAR_HOST_URL: ${{ secrets.URL }}
