# This is a basic workflow to help you get started with Actions
name: sonar-scanner
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan:
    # The type of runner that the job will run on
    runs-on: Warchant/setup-sonar-scanner@v3
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - run: sonar-scanner   -Dsonar.projectKey=AMDM   -Dsonar.sources=.   -Dsonar.host.url=http://vps.bizouarn.fr:9000   -Dsonar.login=2a9eeecff6a451e7d3bf83a5db687bcbd0aeb4b5
